# Configuración general de la aplicación
spring.application.name=productos
server.port=8080
server.servlet.context-path=/api

# Configuración de la conexión a Oracle Cloud con Wallet
spring.datasource.url=jdbc:oracle:thin:@c3cq5y7aelcsqgmu_medium?TNS_ADMIN=./Wallet_C3CQ5Y7AELCSQGMU
# Usando propiedades de archivo externo (application-secrets.properties)
spring.datasource.username=${oracle.db.username}
spring.datasource.password=${oracle.db.password}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración de JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# Configuración de logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.rabbithole=DEBUG
